name: PicCraft
version: "${version}"
main: com.piccraft.plugin.PicCraftPlugin
description: Places PicCraft build plans in the Minecraft world
api-version: "1.21"
authors:
  - PicCraft

commands:
  picclear:
    description: "Clear a PicCraft build"
    usage: "/picclear [job_id|last]"
  piccmove:
    description: "Move a PicCraft build to your current position, facing the same dir as u"
    usage: "/piccmove [job_id|last]"